export const FETCH_NOTES = "FETCH_NOTES";
export const UPDATE_EDITING_NOTE = "UPDATE_EDITING_NOTE";
export const SWITCH_VIEW = "SWITCH_VIEW";
export const FETCH_NOTEBOOKS = "FETCH_NOTEBOOKS";
export const REGISTER = "REGISTER";
